name: Benchmarks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [baseline, tinylfu_admit]         # policies for the main figures
        capacity: [25600, 51200, 102400]        # 50MB, 100MB, 200MB (≈ items)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas matplotlib

      - name: Ensure data/results dirs
        run: mkdir -p data results

      - name: Generate trace if missing (deterministic, CI-friendly)
        run: |
          cat > gen_trace.py <<'PY'
          import json, random, os
          p = "data/freq_wins_50k.jsonl"
          if not os.path.exists(p):
              random.seed(42)
              hot  = [f"hot-{i}"  for i in range(50)]
              cold = [f"cold-{i}" for i in range(2000)]
              with open(p, "w", encoding="utf-8") as f:
                  for _ in range(5000):  # small CI trace so runs are quick
                      key = random.choice(hot) if random.random() < 0.6 else random.choice(cold)
                      f.write(json.dumps({"prompt": key, "response": f"response-for-{key}"}) + "\n")
          print("trace_ready:", p)
          PY
          python gen_trace.py

      - name: Sanity check files
        run: |
          ls -lah
          ls -lah data || true
          head -n 3 data/freq_wins_50k.jsonl || true

      - name: Run ${{ matrix.mode }} at capacity=${{ matrix.capacity }}
        shell: bash
        run: |
          EXTRA=""
          if [ "${{ matrix.mode }}" = "tinylfu_admit" ]; then
            EXTRA="--admit-k 2"
          fi
          python3 bench_gptcache.py \
            --trace data/freq_wins_50k.jsonl \
            --dim 512 \
            --capacity ${{ matrix.capacity }} \
            --base-lat 0.0005 \
            --per-token 0.0002 \
            --mode ${{ matrix.mode }} \
            ${EXTRA} \
            --outdir results

      - name: Upload results for this leg
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ matrix.mode }}-${{ matrix.capacity }}
          path: |
            results/**
            !**/__pycache__/**

  aggregate-plots:
    runs-on: ubuntu-latest
    needs: run-benchmarks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install plotting deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pandas matplotlib

      - name: Download all benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: benchmark-results-*
          path: results
          merge-multiple: true

      - name: Show what we downloaded
        run: |
          ls -R results || true
          find results -name "summary.txt" -maxdepth 3 -print

      - name: Plot results (all legs combined)
        run: |
          if [ -f plot_results.py ]; then
            python3 plot_results.py
          else
            echo "plot_results.py not found; cannot generate plots." && exit 1
          fi

      - name: Upload combined plots & CSV
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-plots
          path: |
            results/plots/**
            results/benchmark_summary.csv
