name: Benchmarks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data/results dirs
        run: mkdir -p data results

      - name: Run baseline
        run: |
          python3 bench_gptcache.py \
            --trace data/freq_wins_50k.jsonl \
            --dim 512 --capacity 102400 \
            --base-lat 0.0005 --per-token 0.0002 \
            --mode baseline

      - name: Run TinyLFU
        run: |
          python3 bench_gptcache.py \
            --trace data/freq_wins_50k.jsonl \
            --dim 512 --capacity 102400 \
            --base-lat 0.0005 --per-token 0.0002 \
            --mode tinylfu_admit

      - name: Generate plots
        run: python3 plot_results.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: results/**
